Add option to filter reviews
apify-projects/store-crawler-google-places pull request #340
Opened 2023-01-25 00:55 UTC by HamzaAlwan

2023-01-25 00:57 UTC, HamzaAlwan commented
@metalwarrior665 Also fixed the issue you mentioned before about extracting `reserveTableUrl`

2023-01-26 12:05 UTC, metalwarrior665 requested changes
Thanks, great job! Just a few minor adjustments

2023-01-26 12:05 UTC, metalwarrior665 commented on src/place-extractors/general.ts
> -            reserveTableUrl: $('a:contains("Reserve a table")').attr('href') || undefined,
Let's maybe keep both `temporarilyClosed` and `reserveTableUrl` extraction fro HTML as backup if there is undefined from JSON? So we keep the HTML parsing around if there would be big problem with the JSON (unlikely but can happen)

Long term plan is to move JSON extraction and HTML extraction to completely separate file and merge only at the very last.

2023-01-26 12:05 UTC, metalwarrior665 commented on src/place-extractors/reviews.ts
> +            if (reviewsSearchString) {
This looks like 2 identical ifs nested

2023-01-26 12:05 UTC, metalwarrior665 commented on src/place-extractors/reviews.ts
> +                    await page.waitForResponse((response) => response.url().includes('preview/review/listentitiesreviews'));
These two lines should be probably in `Promise.all` because this might be a race condition where the response will fire faster than the click returns and you might miss it.

2023-01-26 21:09 UTC, HamzaAlwan commented on src/place-extractors/reviews.ts
> +                    await page.waitForResponse((response) => response.url().includes('preview/review/listentitiesreviews'));
It makes sense, but it should also work if I did this right:
```
page.click(reviewsButtonSel);
await page.waitForResponse((response) => response.url().includes('preview/review/listentitiesreviews'));
```

I went with your suggestion.

2023-01-26 22:52 UTC, metalwarrior665 commented on src/place-extractors/reviews.ts
> +                    await page.waitForResponse((response) => response.url().includes('preview/review/listentitiesreviews'));
This your suggestion would be very bad. If you don't await a Promise or don't attach catch handler, it becomes "free floating" (outside of the sync context). So the try/catch block will not catch it and it will become unhandled rejection which in Node 16+ crashes the whole process.

See here example code: https://console.apify.com/actors/D59Kg961wUx0Q9HNI/runs/VyTpQ85YJQCPQswc6#log

2023-01-26 23:27 UTC, metalwarrior665 requested changes
Just Readme things

2023-01-26 23:27 UTC, metalwarrior665 commented on .actor/INPUT_SCHEMA.json
> +            "description": "If you fill in a keyword(s), only reviews containing the keyword(s) will be scraped. If you leave the field empty, all reviews will be scraped (only reviews presented by G
Sorry, my previous comment was completely wrong, my bad. I thought you are clicking on one of the predefined keywords by Google. But your solution actually types the search into text field which is much better.

So then the `(only those presented by Google for each place)` doesn't really make sense and we can remove it from both the title and description :)

2023-01-26 23:27 UTC, metalwarrior665 commented on README.md
> +For hotels, we also extract the `updatesFromCustomers` field:
Both of these are not only for hotels so we can remove this comment.

1. Also please add these features to the `## What is Google Maps Scraper what does it do?` section as one of the points.
2. I talked with the marketing team and they will eventually split the output example into more sections. So you can start and make a subsections (header starting with ####) for `Updates from customers` and `Questions and answers`. The above markdown section has header `###` so you can still nest one more with `####`

2023-01-26 23:27 UTC, metalwarrior665 commented on README.md
>  ```
I wonder why GitHub has this red color?

2023-01-27 00:22 UTC, HamzaAlwan commented on README.md
>  ```
No idea

2023-01-27 00:36 UTC, HamzaAlwan commented on README.md
> +For hotels, we also extract the `updatesFromCustomers` field:
Like this?

### Updates from customers
#### We also extract the `updatesFromCustomers` field:
``` json
"updatesFromCustomers": {
    "text": "Disneyland California Adventure small area with large park all inclusive celebrations. This is a glimpse into Los Reyes parade.  I'm a true fan. Thanks",
    "language": "en",
    "postDate": "a week ago",
    "postedBy": {
        "name": "Kayla Arredondo",
        "url": "https://www.google.com/maps/contrib/102968882116587973980?hl=en-US",
        "title": "Local Guide",
        "totalReviews": 225
    },
    "media": [
        {
            "link": "https://lh3.googleusercontent.com/ggms/AF1QipNNaoT0NSbcWOPSduvZNqJ0kSqUs-dod32FeBtr=m18",
            "postTime": "a week ago"
        }
    ]
}
```

### Questions and answers
#### We also extract the `questionsAndAnswers` field:
``` json
"questionsAndAnswers": {
    "question": "Which is the best easier way to drop off a family to Disneyland Park",
    "answer": "best way for drop off family is at down town Disney. Drop them off then you can take a short walk to the park. ",
    "askDate": "5 years ago",
    "askedBy": {
        "name": "Cecilia Salcedo",
        "url": "https://www.google.com/maps/contrib/109041536347893604294"
    },
    "answerDate": "5 years ago",
    "answeredBy": {
        "name": "Gabby Lujan",
        "url": "https://www.google.com/maps/contrib/105966144333216697667"
    }
}
```

2023-01-27 09:34 UTC, metalwarrior665 requested changes

2023-01-27 09:34 UTC, metalwarrior665 commented on README.md
What I meant is to just add one sentence here
`- Updates from customers & Questions and answers

2023-01-27 09:34 UTC, metalwarrior665 commented on README.md
> +
1. And this whole example move to the output example section under the `For hotels, we also extract the `moreHotelsOptions` field:`
2. And instead of 
```
### Questions and answers
#### We also extract the `questionsAndAnswers` field:
```

You can do just 
```
#### Questions and answers
```

2023-01-27 16:22 UTC, metalwarrior665 approved these changes

2023-01-27 16:22 UTC, merged